"""Rename mileage to kilometers

Revision ID: 0fc688e628b4
Revises: 
Create Date: 2024-10-23 01:51:35.492876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fc688e628b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('kilometers', sa.Integer(), nullable=True))
    op.drop_column('cars', 'mileage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('mileage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('cars', 'kilometers')
    # ### end Alembic commands ###
